name: mongoose-03-10-2024-dev
services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/server:ro
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
    depends_on:
      - db_mongo
    restart: on-failure
    networks:
      - mongo-bridge-development
    
  db_mongo:
    image: mongo:latest
    volumes:
      - ~/db_mongo:/data/db
    restart: always  
    networks:
      - mongo-bridge-development

networks:
  mongo-bridge-development: {}
