name: fm2024-mongoose-03-10-2024
services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/server:ro
    ports:
      - "8080:3000"
    environment:
      - PORT=3003
    depends_on:
      - db_mongo
    restart: on-failure
    networks:
      - mongo-bridge-development
    configs:
      - httpd-config
    secrets:
      - server-certificate

  db_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /home/marta/freshcode/db_mongo_03_10:/data/db
    networks:
      - mongo-bridge-development

volumes:
  db-data:
    driver: local

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  mongo-bridge-development: {}
